image: docker:latest
services:
  - docker:dind

before_script:
  - apt-get update && apt-get install -y gnupg
  - echo "$GPG_PRIVATE_KEY" | gpg --batch --import
  - echo "use-agent" >> ~/.gnupg/gpg.conf
  - echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
  - echo RELOADAGENT | gpg-connect-agent

stages:
  - build

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

maven-build:
  image: maven:3-jdk-8
  stage: build
  script:
    - echo ${MAVEN_SETTINGS} | base64 -d > settings.xml
    - mvn -s settings.xml clean install deploy
